# -*- coding: utf-8 -*-
"""trainpalm

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GLBI2h9VY7R-CrPUxilg-c_938R14RuF
"""

import os
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras.preprocessing.image import load_img, img_to_array
from sklearn.model_selection import train_test_split

CSV_PATH = 'label_chitay_final.csv'
IMAGE_DIR = '/content/drive/MyDrive/AI_Processed_Pics'
IMG_SIZE = (128, 128)
BATCH_SIZE = 32
EPOCHS = 100


df = pd.read_csv(CSV_PATH)

target_columns = ['sunghiep', 'tridao', 'tamdao', 'sinhdao']

y = df[target_columns].values

def load_and_preprocess_images(image_names, base_dir, target_size):
    images = []
    skipped_files = 0
    for name in image_names:
        img_path = os.path.join(base_dir, name)
        if os.path.exists(img_path):
            img = load_img(img_path, target_size=target_size)
            img_array = img_to_array(img) / 255.0
            images.append(img_array)
        else:
            images.append(np.zeros((target_size[0], target_size[1], 3)))
            skipped_files += 1

    if skipped_files > 0:
        print(f"Cảnh báo: Không tìm thấy {skipped_files} file ảnh trong thư mục!")
    return np.array(images)

print("Đang tải và xử lý toàn bộ ảnh...")
X = load_and_preprocess_images(df['name'].values, IMAGE_DIR, IMG_SIZE)

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

model = models.Sequential([
    layers.Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(IMG_SIZE[0], IMG_SIZE[1], 3)),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu', padding='same'),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(128, (3, 3), activation='relu', padding='same'),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(128, (3, 3), activation='relu', padding='same'),
    layers.MaxPooling2D((2, 2)),
    layers.Flatten(),
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.3),
    layers.Dense(64, activation='relu'),
    layers.Dense(4, activation='linear', name='output_layer')
])

model.compile(optimizer='adam',
              loss='mse',
              metrics=['accuracy'])
model.summary()


print("Bắt đầu huấn luyện...")
history = model.fit(
    X_train, y_train,
    validation_data=(X_val, y_val),
    batch_size=BATCH_SIZE,
    epochs=EPOCHS
)

model.save('ai.h5')

import os
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.image import load_img, img_to_array

MODEL_PATH = 'ai.h5'
IMG_SIZE = (128, 128)

IMAGE_TO_TEST = '11.jpg'

if os.path.exists(MODEL_PATH):
    print(f"Đang tải mô hình từ {MODEL_PATH}...")
    model = tf.keras.models.load_model(MODEL_PATH, compile=False)
    model.compile(optimizer='adam', loss='mse', metrics=['mae'])

    print("Tải và cấu hình lại mô hình thành công!\n")
else:
    print(f"LỖI: Không tìm thấy file mô hình '{MODEL_PATH}'. Hãy kiểm tra lại đường dẫn.")
    exit()

if os.path.exists(IMAGE_TO_TEST):
    img = load_img(IMAGE_TO_TEST, target_size=IMG_SIZE)
    img_array = img_to_array(img) / 255.0
    img_input = np.expand_dims(img_array, axis=0)
else:
    print(f"LỖI: Không tìm thấy ảnh test tại '{IMAGE_TO_TEST}'. Hãy kiểm tra lại.")
    exit()

print(f"Đang phân tích ảnh: {IMAGE_TO_TEST}...")
predictions = model.predict(img_input)
result = predictions[0]
target_columns = ['Sự nghiệp (sunghiep)', 'Trí đạo (tridao)', 'Tâm đạo (tamdao)', 'Sinh đạo (sinhdao)']

print("\n" + "="*40)
print(" KẾT QUẢ DỰ ĐOÁN MỨC ĐỘ ĐƯỜNG CHỈ TAY ")
print("="*40)

for name, value in zip(target_columns, result):
    percentage = value * 100
    if value < 0.3:
        status = "Ngắn / Mờ"
    elif value < 0.7:
        status = "Trung bình"
    else:
        status = "Dài / Rõ nét"

    print(f"- {name}: {value:.4f} ({percentage:.1f}%) -> Đánh giá: {status}")

print("="*40)

